apiVersion: v1
kind: Pod
metadata:
  name: notebook
  namespace: kubeflow
spec:
  containers:
  - name: notebook
    image: fairing-notebook
    ports:
    - containerPort: 8888
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/etc/secrets/user-gcp-sa.json"
    volumeMounts:
    - name: user-gcp-sa
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: user-gcp-sa
    secret:
      secretName: user-gcp-sa
